<div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true">
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
<!-- 

    //............................................................................................................
//..................dddd.................iiii...........................................................llll..
//..................dddd.................iiii...........................................................llll..
//..................dddd................................................................................llll..
//...aaaaaa....ddddddddddmmmmmmmmmmmmm...iiii.nnnnnnnn....... pppppppp....aaaaaa...nnnnnnnn....eeeeee...llll..
//..aaaaaaaa..dddddddddddmmmmmmmmmmmmmm..iiii.nnnnnnnnn...... ppppppppp..aaaaaaaa..nnnnnnnnn..eeeeeeee..llll..
//.aaaa.aaaaaadddd.ddddddmmmm.mmmmmmmmm..iiii.nnnn.nnnnn..... pppp.ppppppaaa.aaaaa.nnnn.nnnnnneee.eeee..llll..
//.....aaaaaaaddd...dddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... ppp...pppp....aaaaaa.nnnn..nnnnneee..eeee.llll..
//..aaaaaaaaaaddd...dddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... ppp...pppp.aaaaaaaaa.nnnn..nnnnneeeeeeeee.llll..
//.aaaaaaaaaaaddd...dddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... ppp...pppppaaaaaaaaa.nnnn..nnnnneeeeeeeee.llll..
//.aaaa.aaaaaaddd...dddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... ppp...pppppaaa.aaaaa.nnnn..nnnnneee.......llll..
//.aaaa.aaaaaadddd.ddddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... pppp.ppppppaaa.aaaaa.nnnn..nnnnneee..eeee.llll..
//.aaaaaaaaaa.dddddddddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... ppppppppp.paaaaaaaaa.nnnn..nnnn.eeeeeeee..llll..
//..aaaaaaaaa..ddddddddddmmm..mmmm..mmmm.iiii.nnnn..nnnn..... pppppppp...aaaaaaaaa.nnnn..nnnn..eeeeee...llll..
//........................................................... ppp.............................................
//........................................................... ppp.............................................
//........................................................... ppp.............................................
//........................................................... ppp.............................................
//............................................................................................................
-->


                <li class="navigation-header apdmod"><span>Main Navigation</span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Admin Panels"></i>
                </li>
                <li id="li_dashboard" class="nav-item apdmod"><a href="dashboard"><i class="las la-tachometer-alt"></i><span class="menu-title" data-i18n="iDashboard">Dashboard</span></a>
                </li>



<!-- 
//...................................................................................
//.iiii............................................ttt...............................
//.iiii...........................................nttt...............................
//................................................nttt...............................
//.iiii.innnnnnn..nvvv..vvvv..eeeeee...ennnnnnn.nnnttttt..oooooo..oorrrrrrry...yyyy..
//.iiii.innnnnnnn.nvvv..vvvv.veeeeeee..ennnnnnnnnnnttttttoooooooo.oorrrrrrryy..yyyy..
//.iiii.innn.nnnnnnvvv.vvvv.vvee.eeee..ennn.nnnnn.nttt..tooo.ooooooorrr..rryy..yyyy..
//.iiii.innn..nnnn.vvvvvvvv.vvee..eeee.ennn..nnnn.nttt.ttoo...oooooorr...rryy.yyyy...
//.iiii.innn..nnnn.vvvvvvvv.vveeeeeeee.ennn..nnnn.nttt.ttoo...oooooorr....ryyyyyyy...
//.iiii.innn..nnnn.vvvvvvv..vveeeeeeee.ennn..nnnn.nttt.ttoo...oooooorr....ryyyyyy....
//.iiii.innn..nnnn..vvvvvv..vvee.......ennn..nnnn.nttt.ttoo...oooooorr.....yyyyyy....
//.iiii.innn..nnnn..vvvvvv..vvee..eeee.ennn..nnnn.nttt..tooo.ooooooorr.....yyyyyy....
//.iiii.innn..nnnn..vvvvv....veeeeeee..ennn..nnnn.nttttttoooooooo.oorr.....yyyyy.....
//.iiii.innn..nnnn...vvvv.....eeeeee...ennn..nnnn.nttttt..oooooo..oorr......yyyy.....
//..........................................................................yyyy.....
//.........................................................................yyyy......
//.......................................................................rryyyy......
//.......................................................................rryyy.......
//...................................................................................
 -->

 <!-- <li class=" navigation-header inarallset"><span>Inventory</span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="InventoryAsset"></i>
</li>

    <li id="li_invent_of_assets" class="li_invent_of_assets nav-item inarallset inaltamod inalalllist"><a href="#"><i class="las la-mobile"></i></i><span class="menu-title" data-i18n="UinMobileapp">Mobile App</span></a>
    </li>
    <li id="li_list_physicalcount" class="li_list_physicalcount inarallset inalzvmod inalalllist"><a class="menu-item" href="#"><i class="las la-hand-spock"></i><span data-i18n="Uinphyscalcount">Physical Count</span></a>
    </li> -->


<!-- 
//.................................................
//...........................................ttt...
//..........................................tttt...
//..........................................tttt...
//...aaaaaa...sssssss...sssssss....eeeeee.eettttt..
//..aaaaaaaa.assssssss.sssssssss..eeeeeeeeeettttt..
//.aaaa.aaaaaasss.ssss.ssss.ssss.seee.eeee..tttt...
//.....aaaaaaassss.....sssss.....seee..eeee.tttt...
//..aaaaaaaaa.ssssss....ssssss...seeeeeeeee.tttt...
//.aaaaaaaaaa..sssssss...sssssss.seeeeeeeee.tttt...
//.aaaa.aaaaa......ssss......ssssseee.......tttt...
//.aaaa.aaaaaasss..ssssssss..ssssseee..eeee.tttt...
//.aaaaaaaaaaassssssss.sssssssss..eeeeeeee..ttttt..
//..aaaaaaaaa..ssssss....ssssss....eeeeee...ttttt..
//.................................................

-->
                <!-- <li class=" navigation-header inarallset"><span>Transactions</span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Asset"></i>
                </li> -->
                <li id="li_livemonitoring" class="nav-item li_livemonitoring"><a href="live_monitoring"><i class="las la-play-circle"></i><span class="menu-title" data-i18n="ilivemonitoring">Live Monitoring</span></a>
                </li>
                <li id="li_attendance_details" class="nav-item li_attendance_details"><a href="attendance_details"><i class="las la-calendar"></i><span class="menu-title" data-i18n="ilivemonitoring">Attendance Details</span></a>
                </li>
                <li id="li_offlinesync" class="nav-item li_offlinesync"><a href="offline_sync"><i class="las la-sync"></i><span class="menu-title" data-i18n="iofflinesync">Import Attendance</span></a>
                </li>
                <!-- <li id="li_assetlist" class="nav-item li_assetlist inarallset inalalllist"><a href="#"><i class="las la-list"></i><span class="menu-title" data-i18n="Transact Asset">Asset Lists</span></a>
                    <ul class="menu-content">
                        <li id="li_list_of_assets" class="li_list_of_assets nav-item inarallset asaltamod inalalllist"><a href="list_of_asset"><span class="menu-title" data-i18n="iListofAssets">Total Assets</span></a>
                        </li>
                        <li id="li_list_zerovalued" class="li_list_zerovalued inarallset asalzvmod inalalllist"><a class="menu-item" href="transact_zero_valued"><i></i><span data-i18n="Utransactzerovalued">Zero Valued Assets</span></a>
                        </li>
                    </ul>
                </li> -->

<!-- 
                <li id="li_transact" class="nav-item li_transact hidefromuser inarallset asatallmod"><a href="#"><i class="las la-sync-alt"></i></i><span class="menu-title" data-i18n="Transact Asset">Asset Transaction</span></a>
                    <ul class="menu-content">
                        <li id="li_transact_add_asset" class="li_transact_add_asset hidefromuser inarallset asatallmod asataumod"><a class="menu-item" href="transact_add_asset"><i></i><span data-i18n="Utransactaddasset">Add / Update Asset</span></a>
                        </li>
                        <li id="li_transact_asset_issuance" class="li_transact_asset_issuance hidefromuser inarallset asatallmod asataimod"><a class="menu-item" href="transact_asset_issuance"><i></i><span data-i18n="Utransactaddassetissuance">Asset Issuance</span></a>
                        </li>
                        <li id="li_transact_asset_return" class="li_transact_asset_return hidefromuser inarallset asatallmod asatarmod"><a class="menu-item" href="transact_asset_return"><i></i><span data-i18n="Utransactaddassetreturn">Asset Return</span></a>
                        </li>
                        <li id="li_transact_asset_repair" class="li_transact_asset_repair hidefromuser inarallset asatallmod asatarepairmod"><a class="menu-item" href="transact_asset_repair"><i></i><span data-i18n="Utransactaddassetrepair">Asset Repair</span></a>
                        </li>
                        <li id="li_transact_asset_lost" class="li_transact_asset_lost hidefromuser inarallset asatallmod asataltmod"><a class="menu-item" href="transact_asset_lost"><i></i><span data-i18n="Utransactaddassetlost">Asset Lost</span></a>
                        </li>
                        <li id="li_transact_asset_dispose" class="li_transact_asset_dispose hidefromuser inarallset asatallmod asatadpmod"><a class="menu-item" href="transact_asset_dispose"><i></i><span data-i18n="Utransactaddassetdispose">Asset Dispose</span></a>
                        </li>
                        <li id="li_transact_asset_multipletransfer" class="li_transact_asset_multipletransfer hidefromuser inarallset asatallmod asatatmamod"><a class="menu-item" href="transact_asset_multi_transfer"><i></i><span data-i18n="Utransactaddassetmultitransfer">Transfer Multiple Asset</span></a>
                        </li>
                    </ul>
                </li> -->
<!-- 
//.................................................................
//.................................................ttt.............
//................................................tttt.............
//................................................tttt.............
//.rrrrrrrr.eeeeee..epppppppp.....oooooo..orrrrrrrttttttsssssss....
//.rrrrrrrreeeeeeee.eppppppppp..ooooooooo.orrrrrrrttttttssssssss...
//.rrrrr..reee.eeee.epppp.ppppp.oooo.oooooorrrr...tttt.tsss.ssss...
//.rrrr...reee..eeeeeppp...pppppooo...ooooorrr....tttt.tssss.......
//.rrrr...reeeeeeeeeeppp...pppppooo...ooooorrr....tttt..ssssss.....
//.rrrr...reeeeeeeeeeppp...pppppooo...ooooorrr....tttt...sssssss...
//.rrrr...reee......eppp...pppppooo...ooooorrr....tttt.......ssss..
//.rrrr...reee..eeeeepppp.ppppp.oooo.oooooorrr....tttt.tsss..ssss..
//.rrrr....eeeeeeee.eppppppppp..ooooooooo.orrr....ttttttssssssss...
//.rrrr.....eeeeee..epppppppp.....oooooo..orrr....tttttt.ssssss....
//..................eppp...........................................
//..................eppp...........................................
//..................eppp...........................................
//..................eppp...........................................
//.................................................................
-->
                <!-- <li class=" navigation-header rereportmod"><span>Reports</span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Reports_as"></i>
                </li>
                <li id="li_report" class="li_report"><a class="menu-item" href="histories"><i></i><span data-i18n="UrepAssettransac">History</span></a>
                </li> -->
                <!-- <li id="li_report_assetprinting" class=" nav-item rereportmod"><a href="report_asset_print"><i class="las la-qrcode"></i><span class="menu-title" data-i18n="TransactPrinasset">Assets Printing</span></a>
                </li> -->
                <!-- <li id="li_report" class="nav-item li_report rereportmod reapmodar"><a href="#"><i class="las la-search"></i><span class="menu-title" data-i18n="Transact Asset">Asset Reports</span></a>
                    <ul class="menu-content">
                        <li id="li_report_asset_report" class="li_report_asset_report rereportmod reapmodar reviaatmod"><a class="menu-item" href="report_asset_transactions"><i></i><span data-i18n="UrepAssettransac">Via Asset Transactions</span></a>
                        </li>
                    </ul>
                </li> -->





<!-- 
//........................................................................
//.......................ttt...ttt..iiii..................................
//......................tttt..tttt..iiii..................................
//......................tttt..tttt........................................
//..sssssss....eeeeee.eettttttttttttiiii.nnnnnnnn....ggggggggg.sssssss....
//.sssssssss..eeeeeeeeeettttttttttttiiii.nnnnnnnnn..gggggggggggssssssss...
//.ssss.ssss.seee.eeee..tttt..tttt..iiii.nnnn.nnnnnngggg.ggggggsss.ssss...
//.sssss.....seee..eeee.tttt..tttt..iiii.nnnn..nnnnnggg...gggggssss.......
//..ssssss...seeeeeeeee.tttt..tttt..iiii.nnnn..nnnnnggg...gggg.ssssss.....
//...sssssss.seeeeeeeee.tttt..tttt..iiii.nnnn..nnnnnggg...gggg..sssssss...
//.......ssssseee.......tttt..tttt..iiii.nnnn..nnnnnggg...gggg......ssss..
//.ssss..ssssseee..eeee.tttt..tttt..iiii.nnnn..nnnnngggg.ggggggsss..ssss..
//.sssssssss..eeeeeeee..ttttttttttttiiii.nnnn..nnnn.gggggggggggssssssss...
//...ssssss....eeeeee...ttttttttttttiiii.nnnn..nnnn..ggggggggg..ssssss....
//........................................................gggg............
//.................................................ngggg.gggg.............
//..................................................ggggggggg.............
//...................................................ggggggg..............
//........................................................................
-->
                <li class=" navigation-header hidefromuser seusallset"><span>Settings</span><i class="la la-ellipsis-h" data-toggle="tooltip" data-placement="right" data-original-title="Settings"></i>
                </li>


                <li id="users" class=" nav-item li_users hidefromuser seusallset seusmod"><a href="users"><i class="la la-user"></i><span class="menu-title" data-i18n="Users">Users</span></a>
                </li>
                <li id="web_setup" class=" nav-item hidefromuser seusallset sewebmod"><a href="web_setup"><i class="las la-globe"></i><span class="menu-title" data-i18n="Web">Web Setup</span></a>
                </li>
                <!-- <li class=" nav-item"><a href="page_blank"><i class="la la-user"></i><span class="menu-title" data-i18n="Users">Page Blank</span></a>
                </li> -->
                

                <li id="li_mainte" class="nav-item li_mainte hidefromuser seusallset semaintemod"><a href="#"><i class="la la-cog"-></i><span class="menu-title" data-i18n="Mintenance">Maintenance</span></a>
                    <ul class="menu-content">
                        <li id="li_mainte_asset_name" class="li_mainte_asset_name hidefromuser semaintemod semainteanmod"><a class="menu-item" href="maintenance_events"><i></i><span data-i18n="Uassetname">Create Events</span></a>
                        </li>
                        <li id="li_mainte_campus" class="li_mainte_campus"><a class="menu-item" href="maintenance_campus"><i></i><span data-i18n="UaCampus">Campus</span></a>
                        </li>
                        <li id="li_mainte_device" class="li_mainte_device"><a class="menu-item" href="maintenance_device"><i></i><span data-i18n="UaDevice">Device</span></a>
                        </li>
                    </ul>
                </li>


                <li id="li_logs" class=" nav-item li_logs"><a href="logs"><i class="las la-history"></i><span class="menu-title" data-i18n="Ulogs">Logs</span></a>
                </li>


            </ul>
        </div>
    </div>
